FastBlog.Web/Areas/Admin/Components/CategoryViewComponent.cs
using FastBlog.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FastBlog.Web.Areas.Admin.Components
{
    [Area("Admin")]
    public class CategoryViewComponent: ViewComponent
    {
        private readonly ICategoryService _categoryService;
        public CategoryViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke(int categoryId)
        {
            ViewBag.CategoryId = categoryId;
            return View(_categoryService.GetAll());
        }
    }
}

FastBlog.Web/Areas/Admin/Controllers/ArticleController.cs
using FastBlog.Models;
using FastBlog.Models.ViewModels;
using FastBlog.Services;
using FastBlog.Services.Crawls;
using FastBlog.Services.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;

namespace FastBlog.Web.Areas.Admin.Controllers
{
    public class ArticleController : AdminController
    {
        private readonly IArticleService _service;
        private readonly ICategoryService _categoryService;
        public ArticleController(IArticleService service,
            ICategoryService categoryService)
        {
            _service = service;
            _categoryService = categoryService;
        }
        [HttpGet]
        public IActionResult List(PagerItem pager, int categoryId = -1)
        {
            PagedList<ArticleEntity> entities = _service.GetPagedList(pager.Page, pager.PageSize, categoryId);
            PagedList<ArticleModel> models = entities.ToPagedModel(entity =>
            {
                ArticleModel model = new ArticleModel
                {
                    Id = entity.Id,
                    CategoryId = entity.CategoryId,
                    Title = entity.Title,
                    Content = entity.Content,
                    CreateTime = entity.CreateTime
                };

                var category = _categoryService.Get(entity.CategoryId);
                model.CategoryTitle = category.Title;
                return model;
            });

            ViewBag.CategoryId = categoryId;
            return View(models);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new ArticleEntity());
        }

        [HttpPost]
        public IActionResult Add(ArticleEntity entity)
        {
            entity.AccountId = Convert.ToInt32(User.FindFirst(x => x.Type == ClaimTypes.Sid).Value);
            int result = _service.Add(entity);
            return Redirect("/admin/article/list");
        }

        [HttpGet]
        public IActionResult Modify(int id)
        {
            return View(_service.Get(id));
        }

        [HttpPost]
        public IActionResult Modify(ArticleEntity entity)
        {
            int result = _service.Update(entity);
            return Redirect($"/admin/article/modify/{entity.Id}");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            int result = _service.Delete(id);
            return Redirect("/admin/article/list");
        }

        [HttpGet]
        public IActionResult Crawl([FromQuery]string url)
        {
            ICrawl crawl = CrawlFactory.Create(url);
            ArticleEntity entity = crawl.Execute();
            return Json(entity);
        }
    }
}

FastBlog.Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FastBlog.Models;
using FastBlog.Models.ViewModels;
using FastBlog.Services;
using FastBlog.Services.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FastBlog.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _service;
        private readonly ICategoryService _categoryService;
        private readonly IAccountService _accountService;
        public ArticleController(IArticleService service,
            ICategoryService categoryService,
            IAccountService accountService)
        {
            _service = service;
            _categoryService = categoryService;
            _accountService = accountService;
        }

        [HttpGet]
        public IActionResult List(PagerItem pager, int categoryId = -1)
        {
            pager.PageSize = 20;
            PagedList<ArticleEntity> entities = _service.GetPagedList(pager.Page, pager.PageSize, categoryId);
            ViewBag.CategoryId = categoryId;
            
            return View(entities);
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            ArticleEntity entity = _service.Get(id);
            if (entity == null) return NotFound();
            ArticleModel model = new ArticleModel
            {
                Id = entity.Id,
                CategoryId = entity.CategoryId,
                Title = entity.Title,
                Content = entity.Content,
                CreateTime = entity.CreateTime
            };

            // 用户
            var account = _accountService.Get(entity.AccountId);
            model.AccountName = account.Name;

            // 分类
            var category = _categoryService.Get(entity.CategoryId);
            model.CategoryTitle = category.Title;

            // 上一篇/下一篇
            ArticleEntity prev = _service.GetPrevById(id);
            ArticleEntity next = _service.GetNextById(id);
            if (prev != null)
            {
                model.Prev = new ArticleModel { Id = prev.Id, Title = prev.Title, CreateTime = prev.CreateTime };
            }
            if (next != null)
            {
                model.Next = new ArticleModel { Id = next.Id, Title = next.Title, CreateTime = next.CreateTime };
            }
            return View(model);
        }
    }
}

FastBlog.Web/Areas/Admin/Views/Article/Add.cshtml
@model ArticleEntity
@{
    ViewBag.Title = "添加文章";
}
<section class="tool-box">
    <a href="javascript:history.go(-1);" class="am-btn am-btn-xs am-btn-default"><i class="am-icon-reply"></i>返回</a>
</section>
<form action="/admin/article/add" method="post" class="am-form am-form-horizontal" onsubmit="return checkValidate();">
    <div class="am-form-group">
        <label class="am-u-sm-2 am-form-label">采集：</label>
        <div class="am-u-sm-10">
            <div class="am-input-group am-input-group-success">
                <input type="text" class="am-form-field" id="url" placeholder="文章采集地址">
                <span class="am-input-group-btn">
                    <button class="am-btn am-btn-success" type="button" title="抓取" onclick="doCrawl()"><span class="am-icon-search"></span></button>
                </span>
            </div>
        </div>
    </div>

    <div class="am-form-group">
        <label class="am-u-sm-2 am-form-label">标题：</label>
        <div class="am-u-sm-10">
            @Html.TextBoxFor(model => model.Title, new { placeholder = "2-100个字符" })
        </div>
    </div>
    <div class="am-form-group">
        <label class="am-u-sm-2 am-form-label">分类：</label>
        <div class="am-u-sm-10">
            @await Component.InvokeAsync("Category")
        </div>
    </div>
    <div class="am-form-group">
        @Html.TextAreaFor(model => model.Content)
    </div>
    <div class="am-form-group">
        <div class="am-u-sm-10 am-u-sm-offset-2">
            <button type="submit" class="am-btn am-btn-primary"><i class="am-icon-check"></i>保存</button>
        </div>
    </div>
</form>

<script src="~/lib/utf8-net/ueditor.config.js"></script>
<script src="~/lib/utf8-net/ueditor.all.js"></script>
<script>
    var editor;
    function checkValidate() {
        var $Title = $("#@Html.IdFor(model => model.Title)"),
            $CategoryId = $("#@Html.IdFor(model => model.CategoryId)");
        if (!/.{2,100}/.test($Title.val())) {
            $Title.focus();
            return false;
        }
        if ($CategoryId.val()==="-1") {
            alert("请选择分类");
            return false;
        }
        if (editor.getContentTxt().length <=0) {
            editor.focus();
            return false;
        }
        return true;
    }

    $(function () {
        editor = UE.getEditor('@Html.IdFor(model=> model.Content)', {
            initialFrameHeight: 400
        });
    });

    function doCrawl() {
        var match = /^((ht|f)tps?):\/\/[\w\-]+(\.[\w\-]+)+([\w\-\.,@@?^=%&:\/~\+#]*[\w\-\@@?^=%&\/~\+#])?$/,
            $url = $("#url");
        if (!match.test($url.val())) {
            $url.focus();
            return;
        }
        $.getJSON("/admin/article/crawl?url=" + $url.val(), function (data) {
            $("#@Html.IdFor(model=> model.Title)").val(data.title);
            editor.setContent(data.content);
        })
    }
</script>

FastBlog.Web/Areas/Admin/Views/Article/List.cshtml
@model PagedList<ArticleModel>
@{
    ViewBag.Title = "文章列表";
}
<section class="tool-box">
    <a href="/admin/article/add" class="am-btn am-btn-xs am-btn-success"><i class="am-icon-plus"></i>添加</a>
</section>
<label>分类查询：</label>
<form id="form_0" action="/admin/article/list" method="get">
    @await Component.InvokeAsync("Category", ViewBag.CategoryId)
    <input type="hidden" name="page" id="page" value="@Model.Page" />
</form>

<table class="am-table am-table-bordered">
    <thead>
        <tr>
            <th>标题</th>
            <th>分类</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Detail", "Article", new { id = item.Id})" target="_blank" title="@item.Title">@item.Title</a>
                </td>
                <td>@item.CategoryTitle</td>
                <td>@item.CreateTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                <td>
                    <a href="/admin/article/modify/@item.Id" title="编辑" class="am-btn am-btn-xs am-btn-secondary">编辑</a>
                    <a href="javascript:doDelete(@item.Id)" title="编辑" class="am-btn am-btn-xs am-btn-danger">删除</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<ul class="am-pagination">
    <li>
        @if (Model.Page <= 1)
        {
            <a href="javascript:void(0);">&laquo; 上一页</a>
        }
        else
        {

            <a href="javascript:doQuery(@(Model.Page -1));">&laquo; 上一页</a>
        }
    </li>
    <li>当前页：@Model.Page | 总页数：@Model.PageCount | 总记录数：@Model.Total</li>
    <li>
        @if (Model.Page >= Model.PageCount)
        {
            <a href="javascript:void(0);">下一页 &raquo;</a>
        }
        else
        {
            <a href="javascript:doQuery(@(Model.Page +1));">下一页 &raquo;</a>
        }
    </li>
</ul>
<script type="text/javascript">
    function doDelete(id) {
        if (confirm("删除数据后不可恢复，确定删除吗？")) {
            window.location.href = "/admin/article/delete/" + id;
        }
    }
    function doQuery(page) {
        $("#page").val(page);
        $("#form_0").submit();
    }

    $("#CategoryId").on("change", function () {
        doQuery(1);
    });
</script>

FastBlog.Web/Areas/Admin/Views/Article/Modify.cshtml
@model ArticleEntity
@{
    ViewBag.Title = "修改文章";
}
<section class="tool-box">
    <a href="javascript:history.go(-1);" class="am-btn am-btn-xs am-btn-default"><i class="am-icon-reply"></i>返回</a>
</section>
<form action="/admin/article/modify" method="post" class="am-form am-form-horizontal" onsubmit="return checkValidate();">
    <div class="am-form-group">
        <label class="am-u-sm-2 am-form-label">标题：</label>
        <div class="am-u-sm-10">
            @Html.TextBoxFor(model => model.Title, new { placeholder = "2-100个字符" })
        </div>
    </div>
    <div class="am-form-group">
        <label class="am-u-sm-2 am-form-label">分类：</label>
        <div class="am-u-sm-10">
            @await Component.InvokeAsync("Category", Model.CategoryId)
        </div>
    </div>
    <div class="am-form-group">
        @Html.TextAreaFor(model => model.Content)
    </div>
    <div class="am-form-group">
        <div class="am-u-sm-10 am-u-sm-offset-2">
            @Html.HiddenFor(model=> model.Id)
            <button type="submit" class="am-btn am-btn-primary"><i class="am-icon-check"></i>保存</button>
        </div>
    </div>
</form>

<script src="~/lib/utf8-net/ueditor.config.js"></script>
<script src="~/lib/utf8-net/ueditor.all.js"></script>
<script>
    var editor;
    function checkValidate() {
        var $Title = $("#@Html.IdFor(model => model.Title)"),
            $CategoryId = $("#@Html.IdFor(model => model.CategoryId)");
        if (!/.{2,100}/.test($Title.val())) {
            $Title.focus();
            return false;
        }
        if ($CategoryId.val()==="-1") {
            alert("请选择分类");
            return false;
        }
        if (editor.getContentTxt().length <=0) {
            editor.focus();
            return false;
        }
        return true;
    }

    $(function () {
        editor = UE.getEditor('@Html.IdFor(model=> model.Content)', {
            initialFrameHeight: 400
        });
    });
</script>