FastBlog.Web/Components/WebCategoryViewComponent.cs
using FastBlog.Models.ViewModels;
using FastBlog.Services;
using FastBlog.Services.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FastBlog.Web.Components
{
    public class WebCategoryViewComponent:ViewComponent
    {
        private readonly ICategoryService _service;
        private readonly IArticleService _articleService;
        public WebCategoryViewComponent(ICategoryService service, IArticleService articleService)
        {
            _service = service;
            _articleService = articleService;
        }

        public IViewComponentResult Invoke()
        {
            List<CategoryEntity> entities = _service.GetAll();
            List<CategoryModel> models = entities.Select(entity =>
            {
                CategoryModel model = new CategoryModel
                {
                    Id = entity.Id,
                    Title = entity.Title,
                    Desc = entity.Desc,
                    Sequence = entity.Sequence,
                    CreateTime = entity.CreateTime,
                    ArticleCount = _articleService.GetCountByCategoryId(entity.Id)
                };
                return model;
            }).ToList();
            return View(models);
        }
    }
}

FastBlog.Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FastBlog.Models;
using FastBlog.Models.ViewModels;
using FastBlog.Services;
using FastBlog.Services.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FastBlog.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _service;
        private readonly ICategoryService _categoryService;
        private readonly IAccountService _accountService;
        public ArticleController(IArticleService service,
            ICategoryService categoryService,
            IAccountService accountService)
        {
            _service = service;
            _categoryService = categoryService;
            _accountService = accountService;
        }

        [HttpGet]
        public IActionResult List(PagerItem pager, int categoryId = -1)
        {
            pager.PageSize = 20;
            PagedList<ArticleEntity> entities = _service.GetPagedList(pager.Page, pager.PageSize, categoryId);
            ViewBag.CategoryId = categoryId;
            
            return View(entities);
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            ArticleEntity entity = _service.Get(id);
            if (entity == null) return NotFound();
            ArticleModel model = new ArticleModel
            {
                Id = entity.Id,
                CategoryId = entity.CategoryId,
                Title = entity.Title,
                Content = entity.Content,
                CreateTime = entity.CreateTime
            };

            // 用户
            var account = _accountService.Get(entity.AccountId);
            model.AccountName = account.Name;

            // 分类
            var category = _categoryService.Get(entity.CategoryId);
            model.CategoryTitle = category.Title;

            // 上一篇/下一篇
            ArticleEntity prev = _service.GetPrevById(id);
            ArticleEntity next = _service.GetNextById(id);
            if (prev != null)
            {
                model.Prev = new ArticleModel { Id = prev.Id, Title = prev.Title, CreateTime = prev.CreateTime };
            }
            if (next != null)
            {
                model.Next = new ArticleModel { Id = next.Id, Title = next.Title, CreateTime = next.CreateTime };
            }
            return View(model);
        }
    }
}

FastBlog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width" />
    <title>@(ViewBag.Title + " - FastBlog")</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link href="~/css/common.css?v=1.2" rel="stylesheet" />
</head>
<body>
    <header id="site-top">
        <div class="layout">
            <h3 class="title">
                <a href="@Url.Action("List", "Article")" title="基于.Net Core轻量级博客系统">FastBlog</a>
                <small>基于.Net Core轻量级博客系统</small>
            </h3>
        </div>
    </header>
    <div id="post-container" class="layout">
        <nav id="navigition">
            <h3>分类</h3>
            @await Component.InvokeAsync("WebCategory")
        </nav>
        <article class="content">
            @RenderBody()
        </article>
    </div>

    <footer id="site-footer">
        <div>
            &copy;2018
            <a href="/">FastBlog</a> 保留所有权利
            <a href="javascript:void(0);" target="_blank">沪ICP备8888888号</a>
        </div>
    </footer>
</body>
</html>